### ISSUE TITLE
code - Formatierung wird nicht entfernt

### ISSUE THREAD

**Issue by AndiLeni** [FriendsOfREDAXO/redactor#13]
Stile wie `code`, `markieren`, o.ä. können nicht entfernt werden.

![gif](https://user-images.githubusercontent.com/13385771/78006410-479ea500-733d-11ea-94c6-b3d4c230543d.gif)

Browser: Firefox
Profil:
```
h3, h4, h5, h6, |, h3, h3,
bold, italic, underline, deleted, style, |,
lists, alignment, block, quote, |,
hr, image, table, |,
linkExternal, linkInternal, linkMedia, |,
html, |,
undo, redo, |,
```

**Comment by tbaddade** [comment]
1. Gibt es irgendwelche JS-Fehler in der Konsole?
1. Warum sind dort drei `h3`-Buttons?
1. Woher kommt das `block`?
1. Was passiert, wenn du den Text nicht markierst sondern nur den Cursor setzt und dann die Formatierung wegnimmst?

**Comment by skerbis** [comment]
Kann ich bestätigen: Firefox 75.0b11 (64-Bit)
und Chrome: Version 80.0.3987.149

Safari hat kein Problem damit

Meine REDACTOR-Config

```
html,undo,|,redo,h1,h2,h3,h4,bold,italic,style,|,image,blockquote,lists[indent],ol,ul,linkExternal,linkInternal,hr,linkYForm[rex_yform_test=last_name|rex_yform_news=title],table,widget
```

**Comment by skerbis** [comment]
@tbaddade https://git.mydomain.tld/assets/core/clipboard-copy-element.js 
net::ERR_ABORTED 404

Kommt das vom Redactor? Es wird nicht geladen

**Comment by tbaddade** [comment]
> Kommt das vom Redactor? Es wird nicht geladen

Nein. Das kommt vom Core.

**Comment by tbaddade** [comment]
Passiert das bei euch auch nur beim `code`? 

`mark` setzen und wegnehmen funktioniert hier im Safari. `code` ist fehlerhaft.

**Comment by skerbis** [comment]
> Passiert das bei euch auch nur beim code?
bestätigt

**Comment by AndiLeni** [comment]
Ich habe keine JS Fehler in der Konsole.
Die doppelten h3 Buttons galten nur als Test, ob Redactor eventuell damit Probleme hat.
Und ihr habt Recht, nur der `code ` Button funktioniert nicht wie er sollte.

**Comment by tbaddade** [comment]
> Die doppelten h3 Buttons galten nur als Test, ob Redactor eventuell damit Probleme hat.

Was bedeutet Test? Denn dein Profil passt nicht zu den Buttons in deinem Gif. Das ist verwirrend, wenn widersprüchliche Angaben gemacht werden.

**Comment by alexplusde** [comment]
Gibt's da nicht immer einen Button zum Entfernen der Formatierung?

**Comment by tbaddade** [comment]
Der Bug lässt sich auch auf deren PlugIn Seite nachvollziehen
https://imperavi.com/redactor/plugins/inlinestyle/

Kann jemand den Bug Imperavi melden? 
https://twitter.com/imperavi

**Comment by tbaddade** [comment]
Der Fehler lässt sich auch auf deren Seite nachstellen. Hab den Fehler gemeldet. Mal sehen was passiert.

**Comment by tbaddade** [comment]
Ist in der aktuellen Verdorr Version immer noch so
https://imperavi.com/redactor/plugins/inlinestyle

**Comment by olien** [comment]
Moin, Habe gerade festgestellt dass ein Klick auf "Cleaner" nicht wirklich "alles"  entfernt. Ist das das gleiche Problem?

**Comment by alxndr-w** [comment]
Der Vendor wird kein Update dazu mehr herausbringen.
