### ISSUE TITLE
Profile durch externe Addons installieren lassen können

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/redactor#14]
Ich würde mir wünschen, dass es auch hier eine Spalte `key` geben wird, die optional befüllt werden kann, sodass Addons Profile hineinsynchronisieren und ggf. updaten können. `key` sollte unique sein, NULL darf erlaubt sein.

**Comment by skerbis** [comment]
Reicht der Name nicht? @alexplusde

**Comment by alexplusde** [comment]
doch, ja, das würde gehen, wenn dieser auch unique ist.

Obacht: Bei cke5 hat beim Reinstallieren / Updaten das Addon immer die id überschrieben. Es sollte also, im Falle von default-Profilen, ein anderes Profil nicht überschrieben werden.

**Comment by skerbis** [comment]
aktuell gibt es keine Default Profile.

**Comment by alexplusde** [comment]
Ok, dennoch bitte berücksichtigen, wenn es ein Default-Profil oder mehrere geben wird.
