### ISSUE TITLE
Texte können nicht mit CMD + V eingefügt werden.

### ISSUE THREAD

**Issue by crydotsnake** [FriendsOfREDAXO/redactor#18]
Texte können nicht mit CMD + V eingefügt werden. u Nach abspeichern eines Textes wird ein `<p>` Tag eingebunden

Mir fallen aktuell keine weiteren Infos ein, die ich hier schreiben könnte. Falls gewünscht, werde ich diese Nachtragen!.

**Comment by skerbis** [comment]
@crydotsnake 

- bitte eine Kurze Überschrift, nicht die komplette Fehlerbeschreibung im Titel. 
- Bitte gebe an, in welcher Umgebung das Problem auftritt, Browser, Version usw.

**Comment by crydotsnake** [comment]
Das Problem tritt in einer Lokalen Installation auf mit REDAXO 5.10.0, und Browser ist Google Chrome auf MacOS. Als Serverumgebung wird MAMP Pro benutzt.

**Comment by tbaddade** [comment]
> Texte können nicht mit CMD + V eingefügt werden. 

Kann ich hier nicht nachvollziehen. Werden irgendwelche JS-Fehler in der Konsole angezeigt?

> Nach abspeichern eines Textes wird ein <p> Tag eingebunden

Der Text erscheint automatisch von einem `<p>` umschlossen. Das ist korrekt.

**Comment by tbaddade** [comment]
ping @crydotsnake

**Comment by crydotsnake** [comment]
Hallo @tbaddade,

Sorry für die späte antwort.

Nein, in der Konsole werden keine JS Fehler angezeigt..

**Comment by tbaddade** [comment]
@skerbis Konntest du das Problem nachstellen?

**Comment by skerbis** [comment]
@tbaddade eben getestet, ich kann das Problem nicht reproduzieren. 
Getestet in: 


        <details>
<summary>System report (REDAXO 5.11.0-dev, PHP 7.3.17, MariaDB 10.2.31)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.11.0-dev |


| PHP           |            |
| ------------: | :--------- |
|       Version | 7.3.17     |
|       OPcache | yes        |
|        Xdebug | no         |


| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.31 |
| Character set | utf8mb4         |


| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | fpm-fcgi   |
|     Webserver | Apache     |


| Request       |                      |
| ------------: | :------------------- |
|       Browser | Chrome/80.0.3987.163 |
|      Protocol | HTTP/1.0             |
|         HTTPS | yes                  |


| Packages          |            |
| ----------------: | :--------- |
|            backup | 2.6.0      |
|          be_style | 2.10.1-dev |
|   be_style/redaxo | 2.10.1-dev |
|           install | 2.8.0-dev  |
|     media_manager | 2.9.1-dev  |
|         mediapool | 2.8.1-dev  |
|          metainfo | 2.7.0      |
|           project | dev        |
|          redactor | 2.0.0      |
|         structure | 2.11.0-dev |
| structure/content | 2.11.0-dev |
|             users | 2.7.0-dev  |
|       zip_install | 1.1        |

</details>

**Comment by skerbis** [comment]
@crydotsnake sind irgendwelche anderen Editoren installiert? 
Alte Redactor-Version z.B.? 

Bitte Systembericht einreichen.

**Comment by crydotsnake** [comment]
Nein, ist eine Frische Installation mit dem redactor addon, und dem developer addon.


        <details>
<summary>System report (REDAXO 5.11.0-dev#5373771be, PHP 7.3.16-1+0~20200320.56+debian10~1.gbp370a75, MariaDB 10.2.31)</summary>

| REDAXO        |                      |
| ------------: | :------------------- |
|       Version | 5.11.0-dev#5373771be |


| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.3.16-1+0~20200320.56+debian10~1.gbp370a75 |
|       OPcache | yes                            |
|        Xdebug | no                             |


| Database      |                 |
| ------------: | :-------------- |
|       Version | MariaDB 10.2.31 |
| Character set | utf8mb4         |


| Server        |               |
| ------------: | :------------ |
|            OS | Linux         |
|          SAPI | fpm-fcgi      |
|     Webserver | Apache/2.4.38 |


| Request       |              |
| ------------: | :----------- |
|       Browser | Firefox/75.0 |
|      Protocol | HTTP/1.1     |
|         HTTPS | yes          |


| Packages          |            |
| ----------------: | :--------- |
|            backup | 2.6.0      |
|          be_style | 2.10.1-dev |
|   be_style/redaxo | 2.10.1-dev |
|         developer | 3.8.0      |
|           install | 2.8.0-dev  |
|     media_manager | 2.9.1-dev  |
|         mediapool | 2.8.1-dev  |
|          metainfo | 2.7.0      |
|           project | dev        |
|          redactor | 2.0.0      |
|         structure | 2.11.0-dev |
| structure/content | 2.11.0-dev |
|             users | 2.7.0-dev  |

</details>

Vielleicht hab ich auch einfach etwas falsch gemacht..

**Comment by crydotsnake** [comment]
Jetzt Konnte ich mit Rechtsklick -> Einfügen einen Text einfügen, aber danach nicht mehr bearbeiten oder etwas an dem Text verändern, auch wenn ich den Block nach dem abspeichern nochmal geöffnet habe...

**Comment by skerbis** [comment]
sorry… aber oben hattest du noch geschrieben **Google Chrome** würdest du verwenden. 
Aber ich kann es auch nicht im Firefox (bei mir 76) nicht reproduzieren.

**Comment by crydotsnake** [comment]
Hm.. Verstehe nicht, was ich falsch mache... Hätte ich Redactor vielleicht über das ZIP Install addon installieren sollen, und nicht mit Git Clonen dürfen?. Das dürfte Ja aber eigentlich keinen Unterschied machen..

**Comment by skerbis** [comment]
Dürfte keinen Unterschied machen. Aber dennoch versuch's mal über das ZIP

**Comment by skerbis** [comment]
Ich mache hier mal zu. Ich kann es weder auf dem Mac noch unter Windows reproduzieren.
