### ISSUE TITLE
Externer Link : Checkbox "externes Fenster" optional

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/redactor#19]
Da wir zumeist das `target` Attribute global für externe Links setzen, kommt es beim Redakteur hier zu Verwirrungen. Dennhakelt er die Checkbox nicht an, wird der Link dennoch sich in einem neuen Tab/Fenster öffnen.

**Comment by skerbis** [comment]
wo definierst du es global?

**Comment by tbaddade** [comment]
> wo definierst du es global?

Das ist ein einfaches `str_replace` kurz bevor der Artikel ausgegeben wird.

**Comment by skerbis** [comment]
Aber nicht in diesem AddOn oder?

**Comment by tbaddade** [comment]
> Aber nicht in diesem AddOn oder?

Nein, wo denkst du hin :)

**Comment by alxndr-w** [comment]
Ich habe gehört, der Editor wird für FOR wegen Lizenzänderungen nicht weiter verfolgt, kann das issue hier dann zu?

**Comment by alxndr-w** [comment]
Die Option lässt sich jetzt mit der aktuellen redactor-Addonversion in den Settings angeben, diesen Parameter hier eingeben:

https://imperavi.com/redactor/docs/settings/link/#s-linknewtab
