### ISSUE TITLE
PlugIn Tabelle : Verbinden von Tabellenzellen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/redactor#20]
Das Vendor PlugIn kopieren und entsprechend erweitern.
Übersetzungen mit einbauen (siehe interne PlugIns)

**Comment by alxndr-w** [comment]
Ich habe gehört, der Editor wird für FOR wegen Lizenzänderungen nicht weiter verfolgt, kann das issue hier dann zu?
