### ISSUE TITLE
Format-Auswahl-Dropdown ermöglichen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redactor#21]
Von der Website: 
<img width="586" alt="Bildschirmfoto 2020-04-28 um 16 00 41" src="https://user-images.githubusercontent.com/791247/80497004-2fd13580-896a-11ea-8b34-b9b34c90df79.png">

**Comment by tbaddade** [comment]
Das hatte ich heute umgesetzt.
https://github.com/FriendsOfREDAXO/redactor/commit/cb969c2edd3782bcf440a72a070571790de2e746

**Comment by skerbis** [comment]
Ups! @tbaddade garnicht gemerkt. Wird sofort getestet.

**Comment by skerbis** [comment]
Funktioniert und ist gefällig 👍

**Comment by tbaddade** [comment]
> Funktioniert

Hattest du auch die Varianten getestet?

- format
- format[p|h1]
- format[Sher=p.sher|Lock=p.lock]

**Comment by skerbis** [comment]
Ja 👍  , schön wäre noch wenn das aktuell aktive Format am Cursor hervorgehoben wäre. Aber ich glaube der Vendor macht es auch nicht.

**Comment by tbaddade** [comment]
>  schön wäre noch wenn das aktuell aktive Format an der Cursor-Position hervorgehoben wäre

Kannst ja als neues Issue erfassen, damit es nicht aus den Augen verloren geht. Vielleicht mag das jemand später noch anpassen.
