### ISSUE TITLE
Math Editor

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/redactor#3]
Hat jemand schon Erfahrungen mit einem gescheiten, leicht integrierbaren Editor für mathematische oder chemische Formeln?

**Liste von Editoren**
https://en.wikipedia.org/wiki/Formula_editor
https://github.com/mathjax/MathJax-docs/wiki/List-of-web-based-math-editors

**Libs** die mir aufgefallen sind (ohne Wertung)
https://mathlive.io
https://ianlucas.github.io/mathjax-editor/
https://katex.org/#demo
https://stackedit.io/app# (Markdwon Editor mit Katex)

**CSS für MathML**
https://www.w3.org/TR/MathML2/appendixg.html

**Comment by alexplusde** [comment]
Wäre das nicht ein Fall für http://phplatex.scarfboy.com/ ?

**Comment by olien** [comment]
Ich hatte mal MathJax benutzt. Ging problemlos.
