### ISSUE TITLE
Bug bei Quellcodebearbeitung

### ISSUE THREAD

**Issue by HassChristian** [FriendsOfREDAXO/redactor#31]
Quellcode Bearbeitung mit Fehler ab Version 5.12. Beim Einfügen von Text oder Bearbeitung von Text verändert sich der schwarze Hintergrund zu weiß. Dadurch wird der Text schwer lesbar. Siehe Bild: 

![screenshot_20210701_194452 (2)](https://user-images.githubusercontent.com/26849978/124253502-5f5c6e80-db28-11eb-97bc-e91c45fb9d67.png)

**Comment by tbaddade** [comment]
Das liegt an dieser Änderung im Core
https://github.com/redaxo/redaxo/commit/1f78fbe7160b1e3000c82e22585f940bf0b132ef#diff-43abea98eb04c3cf2636f7465a3a2cc9334db9c441e7b9a8a77164e801fb8787

@HassChristian Wäre schön, wenn du einen PR erstellen könntest.
