### ISSUE TITLE
Text aus LibreOffice Writer wird im Quelltext umgebrochen

### ISSUE THREAD

**Issue by metaphon** [FriendsOfREDAXO/redactor#39]
Ich verfasse und formatiere die Texte mit Überschriften, Absätzen, Listen etc. in LibreOffice Writer mit einer HTML-Seitenvorlage.
Dort nutze ich einfache HTML-Formatvorlagen (h1, h2, p, ..)

Beim Kopieren von Text aus LibreOffice Writer in das WYSWIG-Feld über wird der Quelltext nach ca. 70 Zeichen umgebrochen.
Beim Redactor 2 wird klappte das noch einwandfrei.

**Comment by tbaddade** [comment]
Wo siehst du ein Problem, wenn der Quelltext umgebrochen wird?

Dein HTML solltest du über den Quellcode einfügen nicht über das WYSWIG-Feld.

**Comment by metaphon** [comment]
Ich kopiere keinen Quelltext ins WYSWIG-Feld sondern wohlformatieren LibreOffice-Text über die Zwischenablage.
Kopiere doch mal den Text aus dem Anhang in ein WYSWIG-Feld eines Redactor-Moduls. Formatierungen werden sauber als HTML-Elemente übernommen!

Da geschieht die wesentliche Formatierung per Textverarbeitung.
[html-vorlage.odt](https://github.com/FriendsOfREDAXO/redactor/files/7883317/html-vorlage.odt)

Spart viel Zeit und Redakteure können die Möglichkeiten ihrer Textverarbeitung nutzen.

Aber manchmal muss ich natürlich im Quellcode nacharbeiten.

**Comment by tbaddade** [comment]
> Kopiere doch mal den Text aus dem Anhang in ein WYSWIG-Feld eines Redactor-Moduls

Ich kann mit der Datei leider nichts anfangen. Ich kann diese zwar öffnen und auch den Inhalt in Redactor kopieren. Ich sehe dann aber vermutlich nicht das was du mir zeigen willst.

Daher, wenn du eine Lösung in Redactor findest die dein Problem behebt, dann erstelle doch gern einen PR oder schreibe hier die Lösung.

**Comment by alxndr-w** [comment]
Hier kam leider keine weitere Fehlerbeschreibung mehr, die weiterhelfen könnte, das Problem zu verstehen.
