### ISSUE TITLE
Wie muss ein Profil / u. Modul aussehen?

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redactor#4]
Ich würde gerne testen, weiß aber nicht was in die Profile soll und wie man das AddOn verwendet

**Comment by tbaddade** [comment]
Ich hatte gehofft es wäre selbsterklärend :)

Bei den PlugIns stehen in der readme und können genauso angegeben werden (es sei denn es steht etwas in Klammern wie beim separator)

```
html,undo,|,redo,h1,h2,h3,h4,bold,italic,|,image,blockquote,lists[indent],ol,ul,linkExternal,linkInternal,hr,linkYForm[rex_yform_test=last_name|rex_yform_news=title],table,widget
```

Verlinkung zu YForm Datensätze

```
linkYForm[rex_yform_test=last_name|rex_yform_news=title]
```
wäre
```
linkYForm[yform_table_a=label|yform_table_b=label|]
```

Es entstehen dann Links wie `yform-table-a://id` die via Output Filter ersetzt werden können [siehe readme](https://github.com/FriendsOfREDAXO/redactor#plugin-linkyform).

**Comment by skerbis** [comment]
thx

**Comment by skerbis** [comment]
rockt! Danke.

**Comment by crydotsnake** [comment]
Wie muss dann das Modul aussehen?.

**Comment by skerbis** [comment]
Erstelle eine Textarea mit der Class des Profils. 

<img width="838" alt="Bildschirmfoto 2020-04-14 um 11 32 52" src="https://user-images.githubusercontent.com/791247/79209460-c585a480-7e43-11ea-98a0-8e1755b6c069.png">

Eingabe: 

```php
 <textarea class="form-control redactor-editor--full" name="REX_INPUT_VALUE[1]">REX_VALUE[1]</textarea>
```

Ausgabe:

```php
REX_VALUE[id="1" output="html"]
```

**Comment by skerbis** [comment]
@crydotsnake gerne zur Readme übertragen.

**Comment by crydotsnake** [comment]
Ich werde mich heute noch darum kümmern 😎 !.

**Comment by crydotsnake** [comment]
Hm. Habe es genauso gemacht wie du beschrieben hattest, aber irgendwie funktioniert es nicht. Muss ich bei `Mindesthöhe` und `Maximalhöhe` etwas eintragen?.

**Comment by skerbis** [comment]
Kann sein, teste mal

**Comment by crydotsnake** [comment]
Es lag daran, das ich bei Zeichenanzahl nichts stehen hatte.

**Comment by skerbis** [comment]
Die Zeichenanzahl kann definitiv leer bleiben

**Comment by crydotsnake** [comment]
Wenn da nichts steht, wird der Editor aber nicht angezeigt.

**Comment by skerbis** [comment]
doch. Bei mir schon

**Comment by crydotsnake** [comment]
Seltsam....

**Comment by crydotsnake** [comment]
Was ich gerade sehe, ich kann mit CMD + V keine Texte einfügen. Wenn ich aber innerhalb des Editor einen Text verfasse & ihn Kopiere, kann ich ihn problemlos einfügen.

**Comment by alexplusde** [comment]
Die offenen/geschlossenen p-Tags sind evtl. daher geschuldet, dass manche Programme, aus denen man kopiert, nicht zwischen einem Absatz und einem Zeilenumbruch unterscheiden können. So werden dann leere Absätze eingefügt.

**Comment by crydotsnake** [comment]
@alexplusde Ich hatte denn Text selber geschrieben und nicht Kopiert. Habe es auch mal von einem Lorem Ipsum generator probiert, dort war auch das gleiche problem das es mit dem kopieren nicht geklappt hat.

**Comment by skerbis** [comment]
@crydotsnake das Thema weicht vom Issue ab. Bitte ein neues Issue anlegen für Probleme mit dem Editor.

**Comment by skerbis** [comment]
Eine erste Anleitung für Profile und Modul befindet sich jetzt in der Readme. Daher hier erstmal close.
