### ISSUE TITLE
fontcolor - eigene Farben definieren

### ISSUE THREAD

**Issue by steri-rex** [FriendsOfREDAXO/redactor#41]
Wie kann man beim Plugin Fontcolor eigene Farben definieren?
Ich hätte es so versucht:
fontcolor[#000|#333]
fontcolor[ '#000', '#333']
fontcolor[#000, #333]
leider funkioniert keine der Varianten - es sind immer alle Farben zu sehen

**Comment by steri-rex** [comment]
danke - wird der PR bzw. die Settings dann in einem neuen Release übernommen? Soll ich lieber auf das neue Release warten?

**Comment by tbaddade** [comment]
Der PR wird nach Änderungen übernommen. Ob du diesen schon verwenden möchtest oder auf das Release warten magst, müsstest du für dich selbst entscheiden.
