### ISSUE TITLE
Tabellenauswahl funktioniert nicht

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/redactor#43]
**Description / Beschreibung**
![image](https://github.com/FriendsOfREDAXO/redactor/assets/3855487/6a566742-9a9a-4b05-b0c1-658eb129a0bd)

Außerdem scheint es bei der Definieriung Probleme mit Label und Tabellenname zu geben - ich muss für beides den Tabellennamen nehmen, weil das Label auch für die Tabelle verwendet wird.

Demo-Zugang kann ich geben.

**Affected versions / Verwendete Versionen**

REDAXO: 5.15
PHP: 8.x
Database: *
Browser: * 
AddOns: *

**Did it whoops? / Whoops erhalten?**
Nein, aber YForm steigt aus.

**Comment by tbaddade** [comment]
> Tabellenauswahl funktioniert nicht

kann ich mit `redactor 2.3.0` und `yform 4.1.1` nicht nachvollziehen.

Im Redactor-Profil habe ich das hinterlegt: `linkYForm[rex_yf_movie=title]`

- linkYForm: Redactor-PlugIn
- rex_yf_movie: YForm-Tabelle
- title: YForm-Value

> Außerdem scheint es bei der Definieriung Probleme mit Label und Tabellenname zu geben - ich muss für beides den Tabellennamen nehmen, weil das Label auch für die Tabelle verwendet wird.

Verstehe ich nicht ganz. Der Fehler oben erscheint, da du als Label das Value `rex_yform_qanda` nutzt, welches jedoch als Feld nicht existiert.

**Comment by alxndr-w** [comment]
Danke für die Rückmeldung. Dann war es ein Konfigurationsfehler. Ich mache solange Mal zu, bis ich wieder Zeit hatte, mich in dem Projekt darum zu kümmern.
