### ISSUE TITLE
Profile bei Installation anlegen

### ISSUE THREAD

**Issue by TobiasKrais** [FriendsOfREDAXO/redactor#48]
Es wäre nützlich, wenn bei der Installation schon ein paar Profile wie full, default und light angelegt werden würden.

**Comment by alxndr-w** [comment]
#50 als Alternative: Beim Erstellen eines Profils wird die Eingabemaske vorbelegt.

**Comment by alxndr-w** [comment]
Ich finde #50 da genügend, das vereinfacht das Anlegen ungemein, ohne in die Doku schauen zu müssen. 

Und wenn man möchte, könnte man im Kontext des Profilanlegens einfach 2-3 Vorschläge für Profile unterhalb des Formulars ausgeben.
