### ISSUE TITLE
Kopieren von Bildern aus anderen Websites vermeiden

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redactor#6]
Aktuell werden Bilder beim Kopieren und Einfügen mit der URL der Quelle eingefügt. 
Das sollte vermieden werden bzw. unterbunden werden können. 

<img width="1059" alt="Bildschirmfoto 2020-03-10 um 15 17 33" src="https://user-images.githubusercontent.com/791247/76321414-48b25880-62e2-11ea-881f-7697b7642b85.png">

**Comment by tbaddade** [comment]
Mag sich jemand das Issue annehmen? Für uns hat es ein sehr geringe Priorität, da wir Bilder nicht im Editor nutzen.

**Comment by skerbis** [comment]
Und genau das möchte ich vermeiden. - Weiß nicht wo ich da ansetzen soll? Kenne das Skript nicht

**Comment by tbaddade** [comment]
> Und genau das möchte ich vermeiden.

Was willst du vermeiden?

**Comment by skerbis** [comment]
Das Bilder gepustet werden. Die sollen entweder über einen Dialog aus dem Medienpool eingefügt werden können oder ganz verboten sein

**Comment by tbaddade** [comment]
Nach dem Ansehen des PRs verstehe ich dich. Du willst das generell unterbinden. Ich dachte dich hörte die "Copyright" Zeile

**Comment by skerbis** [comment]
Ne das "Aus REDAXO.org" kopiert kommt von mir
