### ISSUE TITLE
Eigene redactor.js angeben können

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redactor#8]
Um vielleicht striktere Einstellungen durchführen zu können. Könnte man auch eine eigene redactor.js angeben in den Settings die anstelle der mitgelieferten geladen werden kann.

**Comment by tbaddade** [comment]
Bin mir nicht sicher ob das so gut ist. Einstellungen könnte man auch über das Profil oder über eine allg. Seite definieren. 

Falls sich das JS mal ändern sollte (wegen AddOn oder Redactor 4), dann braucht nicht jeder seine eigenen Dateien anzupassen.

Was meinst du?

**Comment by skerbis** [comment]
Wenn sie so einfach bleibt wie sie jetzt ist, würde meine Variante reichen, denke ich. Der Vorteil wäre eben, dass das AddOn kein Einstellungsmonster wird. Also anders als CKE5.
