### ISSUE TITLE
Tabellen-Funktionen nicht deutsch

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/redactor#9]
<img width="989" alt="Bildschirmfoto 2020-03-10 um 16 02 42" src="https://user-images.githubusercontent.com/791247/76326256-aea1de80-62e8-11ea-8a9a-a2c7c30983cf.png">

**Comment by tbaddade** [comment]
Einige PlugIns kommen direkt vom Vendor. U.a. auch das Tabellen-PlugIn. Hier sind die Übersetzungen direkt im PlugIn enthalten und können nicht über die lang-Datei gesetzt werden.

**Comment by skerbis** [comment]
gibt's n öffentliches Repo, wo man den Entwicklern helfen kann bei der Übersetzung? @tbaddade

**Comment by tbaddade** [comment]
Darum geht es gar nicht. Ich lasse die Übersetzungen je nach Backendsprache des Users ausgeben. Gepflegt werden diese für die internen PlugIns ab [dieser Zeile](https://github.com/FriendsOfREDAXO/redactor/blob/master/lang/de_de.lang#L30).

Will man das für die Tabellen ebenso machen, müsste das externe PlugIn kopiert und angepasst werden. Vielleicht mag das jemand angehen und auch gleich das mergen von Zeilen und Spalten mit erledigen :)
